
services:
  db:
    image: mysql:latest
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todoapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: todo-backend
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=todoapp
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    environment:
      - REACT_APP_API_URL=http://backend:8080
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db-data:
