version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todoapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d

  app:
    image: carrotseo/go-todo
    container_name: todo-app
    environment:
    - DB_HOST=todo-db
    - DB_PORT=3306
    - DB_USER=user
    - DB_PASSWORD=password
    - DB_NAME=todoapp
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
